In [68]:
import torch
import numpy as np
y = torch.randn(2,)
mu = torch.randn(2,)
cov = torch.randn(2,2)**2

ys = torch.randn(10, 2)
mus = torch.randn(10, 2)
covs_ = torch.randn(10, 2)**2
covs = [torch.diag(a) for a in covs_]

In [72]:
log_probs = -0.5*torch.log(2*np.pi*covs_) - 0.5*(mus-ys)
log_probs
torch.randn(2, 4)[:2]

tensor([[ 0.9105, -0.3714, -0.1427, -1.4191],
        [-0.9694, -0.5249,  2.1122,  1.4357]])

In [65]:
diff = y-mu
print(diff)
n = cov.size(-1)
print(n)
cholesky = torch.stack([C.potrf(upper=False) for C in cov.reshape(-1, n, n)])
print(cholesky.shape)
scale_tril = cholesky.view(cov.shape)
print(scale_tril)
print('')
diffs = ys-mus
print(diffs)
n = covs[0].size(-1)
print(n)
Cs = [torch.stack([C.potrf(upper=False) for C in cov.reshape(-1, n, n)]) for cov in covs]
print(Cs)
choleskys = Cs
print(choleskys.shape)



tensor([1.7873, 1.8602])
2
torch.Size([1, 2, 2])
tensor([[0.6957, 0.0000],
        [0.0000, 0.1873]])

tensor([[-0.9321,  0.1350],
        [-1.2903,  1.4760],
        [ 2.4518, -2.1907],
        [ 1.2371,  2.7884],
        [ 1.1902, -0.9435],
        [ 3.9176,  2.2764],
        [ 0.5839,  0.4447],
        [ 2.4473, -0.9120],
        [-1.7844,  0.7896],
        [ 0.4926,  0.0324]])
2
[tensor([[[0.6957, 0.0000],
         [0.0000, 0.1873]]]), tensor([[[0.3399, 0.0000],
         [0.0000, 0.5509]]]), tensor([[[0.6464, 0.0000],
         [0.0000, 1.0711]]]), tensor([[[1.3062, 0.0000],
         [0.0000, 0.6505]]]), tensor([[[0.0270, 0.0000],
         [0.0000, 1.2698]]]), tensor([[[0.1658, 0.0000],
         [0.0000, 0.4640]]]), tensor([[[0.5144, 0.0000],
         [0.0000, 0.3563]]]), tensor([[[0.2862, 0.0000],
         [0.0000, 1.7609]]]), tensor([[[0.5046, 0.0000],
         [0.0000, 0.8852]]]), tensor([[[1.7975, 0.0000],
         [0.0000, 1.3952]]])]


AttributeError: 'list' object has no attribute 'shape'

In [ ]:
        diffs = T[:, self.io_dims[0]:] - self.mu

        n = self.sig[0].size(-1)
        cholesky = torch.stack([C.potrf(upper=False) for C in bmat.reshape((-1, n, n))])
        scale_tril = cholesky.view(bmat.shape)
        scale_tril = _batch_portf_lower(covariance_matrix)

        flat_L = L.unsqueeze(0).reshape((-1,) + L.shape[-2:])
        L_inv = torch.stack([torch.inverse(Li.t()) for Li in flat_L]).view(L.shape)
        M = (x.unsqueeze(-1) * L_inv).sum(-2).pow(2.0).sum(-1)
        M = _batch_mahanobis(self.scale_tril, diff)

        log_det = _batch_diag(self.scale_tril).abs().log().sum(-1)
        log_probs =  -0.5 * (M + self.loc.size(-1) * math.log(2 * math.pi)) - log_det